import { Task, Worker } from "./types";

export const mockTasks: Task[] = [
  {
    id: "task-001",
    title: "开发新闻总结功能",
    description:
      "每 10 分钟爬取最新 AI 新闻，用 ChatGPT 总结，按优先级排列",
    status: "pending",
    priority: "high",
    task_type: "feature",
    engine: "auto",
    routed_engine: null,
    parent_task_id: null,
    sub_tasks: [],
    depends_on: [],
    plan_mode: true,
    plan_content: null,
    assigned_worker: null,
    worktree_branch: null,
    review_status: null,
    review_engine: null,
    review_result: null,
    created_at: "2026-02-20T08:00:00Z",
    started_at: null,
    completed_at: null,
    commit_ids: [],
    error_log: null,
    retry_count: 0,
    max_retries: 3,
  },
  {
    id: "task-002",
    title: "修复文档编辑器中英文间距问题",
    description:
      "中英文之间、中文和数字之间、英文和数字之间自动添加半角空格",
    status: "pending",
    priority: "medium",
    task_type: "bugfix",
    engine: "claude",
    routed_engine: null,
    parent_task_id: null,
    sub_tasks: [],
    depends_on: [],
    plan_mode: false,
    plan_content: null,
    assigned_worker: null,
    worktree_branch: null,
    review_status: null,
    review_engine: null,
    review_result: null,
    created_at: "2026-02-20T08:30:00Z",
    started_at: null,
    completed_at: null,
    commit_ids: [],
    error_log: null,
    retry_count: 0,
    max_retries: 3,
  },
  {
    id: "task-003",
    title: "实现用户认证系统",
    description: "JWT 登录 + 会话管理 + 密码重置功能",
    status: "in_progress",
    priority: "high",
    task_type: "feature",
    engine: "auto",
    routed_engine: "claude",
    parent_task_id: null,
    sub_tasks: [],
    depends_on: [],
    plan_mode: false,
    plan_content: null,
    assigned_worker: "worker-0",
    worktree_branch: "task/task-003-auth",
    review_status: null,
    review_engine: null,
    review_result: null,
    created_at: "2026-02-19T14:00:00Z",
    started_at: "2026-02-19T14:05:00Z",
    completed_at: null,
    commit_ids: ["abc1234"],
    error_log: null,
    retry_count: 0,
    max_retries: 3,
  },
  {
    id: "task-004",
    title: "重构 API 路由模块",
    description: "将路由拆分为独立模块，添加中间件支持",
    status: "in_progress",
    priority: "medium",
    task_type: "refactor",
    engine: "codex",
    routed_engine: "codex",
    parent_task_id: null,
    sub_tasks: [],
    depends_on: [],
    plan_mode: false,
    plan_content: null,
    assigned_worker: "worker-3",
    worktree_branch: "task/task-004-refactor-api",
    review_status: null,
    review_engine: null,
    review_result: null,
    created_at: "2026-02-19T15:00:00Z",
    started_at: "2026-02-19T15:10:00Z",
    completed_at: null,
    commit_ids: [],
    error_log: null,
    retry_count: 0,
    max_retries: 3,
  },
  {
    id: "task-005",
    title: "Review 邮件服务安全性",
    description: "审查邮件发送模块的安全漏洞，检查 XSS 和注入风险",
    status: "reviewing",
    priority: "high",
    task_type: "review",
    engine: "codex",
    routed_engine: "codex",
    parent_task_id: null,
    sub_tasks: [],
    depends_on: [],
    plan_mode: false,
    plan_content: null,
    assigned_worker: "worker-4",
    worktree_branch: null,
    review_status: "in_progress",
    review_engine: "codex",
    review_result: null,
    created_at: "2026-02-19T16:00:00Z",
    started_at: "2026-02-19T16:05:00Z",
    completed_at: null,
    commit_ids: [],
    error_log: null,
    retry_count: 0,
    max_retries: 3,
  },
  {
    id: "task-006",
    title: "优化数据库查询性能",
    description: "分析慢查询日志，添加索引，优化 N+1 问题",
    status: "reviewing",
    priority: "medium",
    task_type: "analysis",
    engine: "auto",
    routed_engine: "codex",
    parent_task_id: null,
    sub_tasks: [],
    depends_on: [],
    plan_mode: false,
    plan_content: null,
    assigned_worker: "worker-3",
    worktree_branch: "task/task-006-db-perf",
    review_status: "pending",
    review_engine: null,
    review_result: null,
    created_at: "2026-02-18T10:00:00Z",
    started_at: "2026-02-18T10:10:00Z",
    completed_at: null,
    commit_ids: ["def5678"],
    error_log: null,
    retry_count: 0,
    max_retries: 3,
  },
  {
    id: "task-007",
    title: "实现会议安排功能",
    description: "自动从日历获取会议信息，生成准备材料",
    status: "completed",
    priority: "high",
    task_type: "feature",
    engine: "auto",
    routed_engine: "claude",
    parent_task_id: null,
    sub_tasks: [],
    depends_on: [],
    plan_mode: true,
    plan_content: "1. 集成 Google Calendar API\n2. 实现会议提醒\n3. 自动生成议程",
    assigned_worker: "worker-1",
    worktree_branch: "task/task-007-meeting",
    review_status: "passed",
    review_engine: "codex",
    review_result: null,
    created_at: "2026-02-17T09:00:00Z",
    started_at: "2026-02-17T09:05:00Z",
    completed_at: "2026-02-17T09:25:00Z",
    commit_ids: ["ghi9012", "jkl3456"],
    error_log: null,
    retry_count: 0,
    max_retries: 3,
  },
  {
    id: "task-008",
    title: "添加语音输入 Whisper 集成",
    description: "使用 OpenAI Whisper API 实现语音转文字",
    status: "completed",
    priority: "medium",
    task_type: "feature",
    engine: "claude",
    routed_engine: "claude",
    parent_task_id: null,
    sub_tasks: [],
    depends_on: [],
    plan_mode: false,
    plan_content: null,
    assigned_worker: "worker-0",
    worktree_branch: "task/task-008-whisper",
    review_status: "passed",
    review_engine: "codex",
    review_result: null,
    created_at: "2026-02-16T11:00:00Z",
    started_at: "2026-02-16T11:05:00Z",
    completed_at: "2026-02-16T11:20:00Z",
    commit_ids: ["mno7890"],
    error_log: null,
    retry_count: 0,
    max_retries: 3,
  },
  {
    id: "task-009",
    title: "文档导出功能开发失败",
    description: "PDF 导出时中文字体渲染异常",
    status: "failed",
    priority: "low",
    task_type: "feature",
    engine: "claude",
    routed_engine: "claude",
    parent_task_id: null,
    sub_tasks: [],
    depends_on: [],
    plan_mode: false,
    plan_content: null,
    assigned_worker: "worker-2",
    worktree_branch: "task/task-009-pdf",
    review_status: null,
    review_engine: null,
    review_result: null,
    created_at: "2026-02-15T14:00:00Z",
    started_at: "2026-02-15T14:05:00Z",
    completed_at: null,
    commit_ids: [],
    error_log: "puppeteer 中文字体加载失败，尝试 3 次后放弃",
    retry_count: 3,
    max_retries: 3,
  },
  {
    id: "task-010",
    title: "旧版通知系统移除",
    description: "移除基于轮询的旧通知系统，已被 WebSocket 替代",
    status: "cancelled",
    priority: "low",
    task_type: "refactor",
    engine: "auto",
    routed_engine: null,
    parent_task_id: null,
    sub_tasks: [],
    depends_on: [],
    plan_mode: false,
    plan_content: null,
    assigned_worker: null,
    worktree_branch: null,
    review_status: null,
    review_engine: null,
    review_result: null,
    created_at: "2026-02-14T10:00:00Z",
    started_at: null,
    completed_at: null,
    commit_ids: [],
    error_log: null,
    retry_count: 0,
    max_retries: 3,
  },
  {
    id: "task-011",
    title: "实现邮件收发模块",
    description: "IMAP 接收 + SMTP 发送，支持附件和 HTML 邮件",
    status: "completed",
    priority: "high",
    task_type: "feature",
    engine: "auto",
    routed_engine: "claude",
    parent_task_id: null,
    sub_tasks: [],
    depends_on: [],
    plan_mode: false,
    plan_content: null,
    assigned_worker: "worker-1",
    worktree_branch: "task/task-011-email",
    review_status: "passed",
    review_engine: "codex",
    review_result: null,
    created_at: "2026-02-15T09:00:00Z",
    started_at: "2026-02-15T09:10:00Z",
    completed_at: "2026-02-15T09:35:00Z",
    commit_ids: ["pqr1234"],
    error_log: null,
    retry_count: 0,
    max_retries: 3,
  },
  {
    id: "task-012",
    title: "安全审计全站 XSS 漏洞",
    description: "扫描所有用户输入点，确认 HTML 转义正确",
    status: "completed",
    priority: "high",
    task_type: "audit",
    engine: "codex",
    routed_engine: "codex",
    parent_task_id: null,
    sub_tasks: [],
    depends_on: [],
    plan_mode: false,
    plan_content: null,
    assigned_worker: "worker-4",
    worktree_branch: null,
    review_status: "passed",
    review_engine: "claude",
    review_result: null,
    created_at: "2026-02-16T14:00:00Z",
    started_at: "2026-02-16T14:05:00Z",
    completed_at: "2026-02-16T14:15:00Z",
    commit_ids: [],
    error_log: null,
    retry_count: 0,
    max_retries: 3,
  },
];

export const mockWorkers: Worker[] = [
  {
    id: "worker-0",
    engine: "claude",
    port: 5200,
    worktree_path: "/app/worktrees/worker-0",
    status: "busy",
    capabilities: ["feature", "bugfix", "plan"],
    current_task_id: "task-003",
    pid: 12345,
    started_at: "2026-02-20T08:00:00Z",
    total_tasks_completed: 42,
    health: {
      last_heartbeat: "2026-02-20T10:05:00Z",
      consecutive_failures: 0,
      avg_task_duration_ms: 240000,
    },
  },
  {
    id: "worker-1",
    engine: "claude",
    port: 5201,
    worktree_path: "/app/worktrees/worker-1",
    status: "idle",
    capabilities: ["feature", "bugfix", "plan"],
    current_task_id: null,
    pid: null,
    started_at: null,
    total_tasks_completed: 38,
    health: {
      last_heartbeat: "2026-02-20T10:04:00Z",
      consecutive_failures: 0,
      avg_task_duration_ms: 200000,
    },
  },
  {
    id: "worker-2",
    engine: "claude",
    port: 5202,
    worktree_path: "/app/worktrees/worker-2",
    status: "idle",
    capabilities: ["feature", "bugfix", "plan"],
    current_task_id: null,
    pid: null,
    started_at: null,
    total_tasks_completed: 35,
    health: {
      last_heartbeat: "2026-02-20T10:03:00Z",
      consecutive_failures: 0,
      avg_task_duration_ms: 260000,
    },
  },
  {
    id: "worker-3",
    engine: "codex",
    port: 5203,
    worktree_path: "/app/worktrees/worker-3",
    status: "busy",
    capabilities: ["review", "refactor", "analysis", "audit"],
    current_task_id: "task-004",
    pid: 12350,
    started_at: "2026-02-20T09:00:00Z",
    total_tasks_completed: 28,
    health: {
      last_heartbeat: "2026-02-20T10:05:00Z",
      consecutive_failures: 0,
      avg_task_duration_ms: 120000,
    },
  },
  {
    id: "worker-4",
    engine: "codex",
    port: 5204,
    worktree_path: "/app/worktrees/worker-4",
    status: "busy",
    capabilities: ["review", "refactor", "analysis", "audit"],
    current_task_id: "task-005",
    pid: 12355,
    started_at: "2026-02-20T09:30:00Z",
    total_tasks_completed: 25,
    health: {
      last_heartbeat: "2026-02-20T10:05:00Z",
      consecutive_failures: 0,
      avg_task_duration_ms: 110000,
    },
  },
];
